services:
  comfyui:
    build: .
    ports:
      - "8188:8188"
    volumes:
      - ./models:/comfyui/models
      - ./output:/comfyui/output
      - ./custom_nodes:/comfyui/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

