services:
  comfyui:
    tty: true
    build: .
    # user: ${MY_UID}:${MY_GID}
    ports:
      - "8188:8188"
    volumes:
      - ./:/comfyui
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

