services:
  comfyui:
    build: .
    ports:
      - "8188:8188"
    volumes:
      - ./:/comfyui
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

